#!/bin/sh

# second layer counterblock API
(
while [ 1 ]; do
	sleep 120
	counterblock
done
) &

# main counterparty-server process
(
sleep 60
while [ 1 ]; do
	sleep 120
	counterparty-server start
done
) &

# patched bitcoin daemon
bitcoind -daemon

while [ 1 ]; do
	echo DOCKER WAIT TICKER `date`
	sleep 60
done
