#!/bin/sh
OLDPATH=$PATH

SCRIPTDIR="`dirname \"$0\"`"
NODE="`cd \"$SCRIPTDIR\" && pwd`"
WHEREAMI=`pwd`

export PATH=$NODE/node_binaries/bin:"$PATH"

node "$NODE/lib/hstat.js" $@

cd "$WHEREAMI"
export PATH="$OLDPATH"
