#!/bin/sh
OLDPATH=$PATH
WHEREAMI=`pwd`
export PATH=$WHEREAMI/node_binaries/bin:"$PATH"
NODEINST=`which node`

if [ "$1" = "" ]; then

  echo " [i] Starting hybridd..."
  NODE_VERSION=$($NODEINST --version)


  if [ "$NODE_VERSION" != "v8.11.2" ]; then
      echo " [!] Warning: hybridd expects Node v8.11.2. found $NODE_VERSION"
      echo "             $NODEINST"
      read -n 1 -p " [?] Do you wish to continue y/n?" CONFIRM
      if [ "$CONFIRM" = "n" ]; then
          PATH=$OLDPATH
          echo "\n [i] Stopped hybridd."
          exit 0
      fi
  else
      echo " [i] using node executable $NODEINST $NODE_VERSION "
  fi


  cd lib
        echo
        mkdir -p $WHEREAMI/var/log
        node hybridd.js 2>&1 | tee $WHEREAMI/var/log/hybridd.log
        echo
        echo " [i] Stopped hybridd."
        echo
elif [ "$1" = "start" ]; then
  ./hybridd.start
else
    cd lib
    node hcmd.js $@
fi

PATH=$OLDPATH
