#!/bin/sh
OLDPATH=$PATH
WHEREAMI=`pwd`
export PATH=$WHEREAMI/node_binaries/bin:"$PATH"
NODEINST=`which node`

if [ "$1" = "" ]; then

  echo " [i] starting hybridd..."
  NODE_VERSION=$($NODEINST --version)

  if [ "$NODE_VERSION" != "v8.12.0" ]; then
      echo " [!] Warning: hybridd expects Node v8.12.0. found $NODE_VERSION"
      echo "             $NODEINST"
      read -p " [?] Do you wish to continue? [y/N] " CONFIRM
      if [ "$CONFIRM" != "y" ]; then
          PATH=$OLDPATH
          echo "\n [i] Stopped hybridd."
          exit 0
      fi
  else
      echo " [i] using node executable $NODEINST $NODE_VERSION "
  fi


  cd lib
  mkdir -p $WHEREAMI/var/log
  node hybridd.js 2>&1 | tee $WHEREAMI/var/log/hybridd.log
  echo " [i] stopped hybridd"
  echo
elif [ "$1" = "start" ]; then
  ./hybridd.start
else
    cd lib
    node hcmd.js $@
fi

PATH=$OLDPATH
