#!/bin/sh

#get current branch reference
ref=$(git symbolic-ref HEAD)
prefix="refs/heads/issue/"
issueBranch=${ref#$prefix}
#extract issue nr (expecting branchname to be "issue/$issueNr-$issueName"
issueNr=$(echo $issueBranch | grep -o  '^[0-9]\+')

if [[ $issueNr =~ ^-?[0-9]+$ ]];then
    #append issue nr to commit message
    echo " #$issueNr" >> $1
fi
